name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build App
        run: npm install && npm run build

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem


      - name: Copy deploy script
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ vars.SERVER_USER }}@${{ vars.SERVER_PUBLIC_IP }} "\
            sudo docker run -p 80:80 -p 443:443 -d --env APP_HOST=app.game7app.com shanaziz/game7-app-angular:${{ steps.meta.outputs.commit_hash }}"
